#!/bin/bash

swaylock \
  --color "#282828" \
  --ring-color "#fabd2f" \
  --inside-color "#282828" \
  --line-color "#3c3836" \
  --key-hl-color "#b8bb26" \
  --ring-ver-color "#b8bb26" \
  --inside-ver-color "#282828" \
  --text-ver-color "#b8bb26" \
  --ring-wrong-color "#fb4934" \
  --inside-wrong-color "#282828" \
  --text-wrong-color "#fb4934" \
  --show-failed-attempts \
  --indicator-radius 10
